language: php

dist: trusty

php:
  - 7.1
  - 7.2

install:
  - composer install
  - ./vendor/bin/simple-phpunit install

script:
  - mkdir -p build/logs
  - ./vendor/bin/simple-phpunit -v --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v